name = "curioustube"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "."

[[build.upload]]
format = "modules"
dir = "dist"
main = "./index.js"

[vars]
NODE_ENV = "production"